"""Typed data models used across the batch assessment pipeline."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path


@dataclass
class DealInput:
    """A discovered deal folder/file and the supported documents it contains."""

    deal_id: str
    path: Path
    supported_files: list[Path]
    latest_modified_at: datetime


@dataclass
class EvidenceBlock:
    """A single extracted text block with provenance."""

    source_path: Path
    text: str


@dataclass
class EvidenceBundle:
    """Aggregated extracted text plus extraction warnings."""

    evidence_blocks: list[EvidenceBlock] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)


@dataclass
class InvestorProfile:
    """Normalized investor preferences used for scoring and fit checks."""

    region: str = ""
    currency: str = ""
    inferred_risk_level: str = ""
    ticket_typical: float = 0
    ticket_min: float | None = None
    ticket_max: float | None = None
    evaluation_weight_overrides: dict[str, float] = field(default_factory=dict)
    return_hurdle: float | None = None
    remaining_angel_budget: float | None = None
    sectors_themes: list[str] = field(default_factory=list)
    geo_focus: list[str] = field(default_factory=list)


@dataclass
class AssessmentResult:
    """Normalized single-deal assessment plus derived scoring outputs."""

    deal_id: str
    company_name: str
    category_scores: dict[str, float | None]
    risk_flags: list[str]
    sectors: list[str]
    geographies: list[str]
    rationale: str
    citations: list[dict[str, object] | str] = field(default_factory=list)
    category_rationales: dict[str, str] = field(default_factory=dict)
    web_sweep_findings: list[dict[str, object] | str] = field(default_factory=list)
    web_sweep_sources: list[dict[str, object] | str] = field(default_factory=list)
    milestones_to_monitor: list[str] = field(default_factory=list)
    key_unknowns: list[str] = field(default_factory=list)
    return_scenarios: list[dict[str, object]] = field(default_factory=list)
    assessment_limitations: str = ""
    assessment_process: dict[str, object] = field(default_factory=dict)
    evidence_sources: list[str] = field(default_factory=list)
    extraction_warnings: list[str] = field(default_factory=list)
    hypothetical_investment: float = 0.0
    investment_currency: str = "EUR"
    investment_basis: str = "not_configured"
    dilution_assumption: str = "Not recorded; do not infer dilution from narrative."
    verdict_one_liner: str = ""
    why_not_invest_now: list[str] = field(default_factory=list)
    what_would_upgrade_to_invest: list[str] = field(default_factory=list)
    market_context: str = ""
    reconciliation_gaps: list[str] = field(default_factory=list)
    fit_call: str = ""
    founder_questions: list[str] = field(default_factory=list)
    weighted_score: float | None = None
    verdict: str = ""
    attention_flag: bool = False
    attention_reason: str = ""
    profile_fit: float = 0.0
    schema_version: int = 1
    category_drivers: dict[str, str] = field(default_factory=dict)
    category_confidence: dict[str, str] = field(default_factory=dict)
    effective_weights: dict[str, float] = field(default_factory=dict)
    score_coverage: float = 0.0
    deal_snapshot: dict[str, str] = field(default_factory=dict)
    decision: dict[str, object] = field(default_factory=dict)
    diligence_issues: list[dict[str, object]] = field(default_factory=list)
    questions: list[dict[str, object]] = field(default_factory=list)
    return_assumptions: dict[str, object] = field(default_factory=dict)
    return_summary: dict[str, object] = field(default_factory=dict)
    recommended_investment: float = 0.0
    decision_reason: str = ""
    next_action: str = ""
    sizing_reason: str = ""
    decision_warnings: list[str] = field(default_factory=list)
    investor_constraints: dict[str, object] = field(default_factory=dict)

    def to_json_dict(self) -> dict[str, object]:
        """Serialize the dataclass to a JSON-compatible dictionary.
        
        Args:
            None.
        
        Returns:
            dict[str, object]: Value returned by this function.
        """

        return asdict(self)


@dataclass
class BatchOutputPaths:
    """Filesystem paths for artifacts generated by a batch run."""

    markdown_path: Path
    csv_path: Path
    json_path: Path
    html_path: Path | None = None
    pdf_path: Path | None = None
